# Generated by Django 4.0.3 on 2022-03-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uinversity',
            new_name='university',
        ),
    ]
